def Menu_Principal(): 
    print ("")
    print("╔════════════════════════════════════╗".center(120))
    print("║            MENÚ PRINCIPAL          ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Coordinador                     ║".center(120))
    print("║ 2. Trainer                         ║".center(120))
    print("║ 3. Camper                          ║".center(120))
    print("║ 4. Lista de Reportes               ║".center(120))
    print("║ 5. Salir                           ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 

def Menu_Coordinador (): 
    print ("")
    print("╔════════════════════════════════════╗".center(120))
    print("║          MENÚ DEL COORDINADOR      ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Listas Campers/Trainers         ║".center(120))
    print("║ 2. Registrar Campers/Trainers      ║".center(120))
    print("║ 3. Asignar Notas                   ║".center(120))
    print("║ 4. Rutas                           ║".center(120))
    print("║ 5. Matriculas                      ║".center(120))
    print("║ 6. Salir del Sistema               ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ").rjust(20))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 

def Menu_Trainer (): 
    print("╔════════════════════════════════════╗".center(120))
    print("║            MENÚ TRAINER            ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Ver Campers y Salón             ║".center(120))
    print("║ 2. Agregar Modulos                 ║".center(120))
    print("║ 3. Asignar Notas                   ║".center(120))
    print("║ 4. Salir                           ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 
    
def Menu_Estudiantes() : 
    print("╔════════════════════════════════════╗".center(120))
    print("║           MENÚ CAMPER              ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Ver Mi Curso                    ║".center(120))
    print("║ 2. Ver Mis Notas                   ║".center(120))
    print("║ 3. Consultar Mi Estado             ║".center(120))
    print("║ 4. Salir                           ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("=====================================".rjust(20))
    print ("")
    return opc 

def Lista_Reportes() : 
    print("╔════════════════════════════════════════╗".center(120))
    print("║          MENÚ LISTA DE REPORTES        ║".center(120))
    print("╠════════════════════════════════════════╣".center(120))
    print("║ 1. Listar Campers Inscritos            ║".center(120))
    print("║ 2. Listar Campers que Aprobaron        ║".center(120))
    print("║    Examen Inicial                      ║".center(120))
    print("║ 3. Listar Entrenadores de CampusLands  ║".center(120))
    print("║ 4. Listar Campers con Bajo Rendimiento ║".center(120))
    print("║ 5. Listar Campers y Trainers Asociados ║".center(120))
    print("║    a una Ruta de Entrenamiento         ║".center(120))
    print("║ 6. Mostrar Estadísticas de Módulos por ║".center(120))
    print("║    Ruta de Entrenamiento y Entrenador  ║".center(120))
    print("║ 7. Estudiantes Estada Riesgo           ║".center(120))
    print("║ 8. Salir                               ║".center(120))
    print("╚════════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 


